name: CD

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # needed for the whisper.cpp submodule
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run ci
      # - run: npm test
      - run: npm run build:docs

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy-docs:
    runs-on: ubuntu-latest
    name: Deploy Docs

    # currently, we cannot deploy from tags
    if: false

    permissions:
      pages: write
      id-token: write

    needs: test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  publish-package:
    runs-on: ubuntu-latest

    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # needed for the whisper.cpp submodule

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
